
import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider";


export const metadata: Metadata = {
  title: "Store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ReduxProvider>

        {children}
        </ReduxProvider>

      </body>
    </html>
  );
}
