
import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider";
import NavbarWrapper from "@/components/NavbarWrapper";
import { AuthProvider } from "@/Context/AuthContext";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <NavbarWrapper />          {/* ⬅️ show navbar on all pages */}
          <main>{children}</main>
          <Toaster position="top-right" />
          </AuthProvider>
        </ReduxProvider>

      </body>
    </html>
  );
}
